version: "3.3"

services:
  loki:
    image: grafana/loki:2.0.0
    container_name: loki
    command: -config.file=/mnt/config/loki-config.yml
    restart: unless-stopped
    user: "1000"
    volumes:
      - ./loki-config.yml:/mnt/config/loki-config.yml
      - /srv/dev-disk-by-uuid-9111da9d-0af8-41d4-ada0-5951e47aad5c/Buffer/loki:/loki
    ports:
      - 3100:3100

  grafana:
    image: grafana/grafana:7.2.2
    container_name: grafana
    restart: unless-stopped
    user: "1000"
    volumes:
      - /srv/dev-disk-by-uuid-9111da9d-0af8-41d4-ada0-5951e47aad5c/Buffer/grafana:/var/lib/grafana
    ports:
      - 3000:3000
